name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # jalan setiap tengah malam UTC
  workflow_dispatch:     # bisa manual dari Actions

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: kanigaraa
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push generated files
        run: |
          mkdir -p output
          cp dist/* output/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/
          git commit -m "update pacman graph" || echo "No changes"
          git push
