name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman graph
        uses: yoshi389111/github-contribution-grid-snake@main
        with:
          color_snake: 'yellow'
          color_dots: 'green'

      - name: Push Pacman graph
        run: |
          mkdir -p output
          mv dist/pacman-contribution-graph.svg output/
          mv dist/pacman-contribution-graph-dark.svg output/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/
          git commit -m "update pacman graph" || echo "No changes to commit"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
