name: Generate Pacman Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: yoshi389111/github-profile-3d-contrib@master
        with:
          username: kanigaraa
          output_dir: output
          theme: pacman

      - name: Push SVG to Repo
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add output/
          git commit -m "update pacman graph" || echo "No changes"
          git push
